context:
  version: "0.0.18"

package:
  name: khiops-driver-azure
  version: ${{ version }}

source:
  - url: https://github.com/KhiopsML/khiopsdriver-azure/archive/refs/tags/${{ version }}.tar.gz
    sha256: 5ee53874e9c88c99d3f7b2891af31870a330675a4edc5dfe732ecb73e22796ee
  - url: https://github.com/KhiopsML/khiopsdriver-shared/archive/6b067e9cba39cdd2be4d0c32b64914ca9c98ce3b.tar.gz
    sha256: a033689e6d2694005834999b404869f9fc35c308eeae17cad26e0c4a0a6f54c4
    target_directory: shared

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - spdlog
    - azure-identity-cpp ==1.13.0
    - azure-storage-blobs-cpp ==12.14.0
    - azure-storage-files-shares-cpp ==12.14.0

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/lib/libkhiopsdriver_file_azure${SHLIB_EXT}
        else:
          - if not exist %PREFIX%\Library\bin\libkhiopsdriver_file_azure.dll exit 1

about:
  homepage: https://khiops.org
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: Khiops driver to access files on Azure Cloud Storage
  description: The Azure driver plugin extends Khiops to enable processing of data files located on Azure Cloud Storage

extra:
  recipe-maintainers:
    - tristandeb1
    - sgouache
